java_binary(
  name = "cedict2odict",
  srcs = glob(["**/*.java"]),
  deps = ['@commons_lang3//jar', '@commons_io//jar'],
  main_class = 'com.odict.cedict2odict.Main',
  visibility = ['//visibility:public']
)